/* ============================================================
   THE ANGELS — الملائكة
   ============================================================
   Every angel the Prophet ﷺ met or described on the night of the
   Isra and the Mi'raj, every angel named or described in the
   Quran, and what the two Sahihs add — in detail, not in outline.

   Each entry carries `points`: the specific things narrated about
   that angel, one by one, each with its own reference.

   Sources read before anything was written:
     Bukhari 349, 3207, 3239, 3236, 3232, 3231, 3225, 3237, 4935,
     6408, 555, 445, 50; Muslim, Books of Faith, Dhikr and Zuhd.

   And the rule that governs the whole site: where something is
   famous but NOT in the Quran or the two Sahihs, the entry says
   so. That applies to a great deal of what is repeated about
   Israfil in particular — his eyes, his size, that he has never
   blinked. Those are not in the two Sahihs, and this file says
   which of it is established and which is not.
   ============================================================ */

const ANGEL_GROUPS = [
  { id: "miraj",  en: "On the night of the Mi'raj", ar: "ليلة الإسراء والمعراج", icon: "🌙" },
  { id: "named",  en: "The named angels",           ar: "الملائكة المُسمَّون",   icon: "⭐" },
  { id: "quran",  en: "Named in the Quran",         ar: "المذكورون في القرآن",   icon: "📖" },
  { id: "sahih",  en: "Around you every day",       ar: "معك في يومك",          icon: "📚" },
  { id: "notest", en: "Famous but not established",  ar: "مشهورٌ غير ثابت",       icon: "⚠️" }
];

const ANGELS = [

  /* ================= THE NAMED ANGELS — in depth ================= */
  {
    id: "ang-israfil",
    group: "named",
    order: 1,
    name: "Israfil — the Trumpet, and the two blasts",
    nameAr: "إسرافيل — الصُّور والنفختان",
    role: "The angel charged with the Trumpet",
    roleAr: "الملَك الموكَّل بالصُّور",
    detail: "Of all the angels, this is the one whose task ends the world and then restarts it. His name is established, his job is established, and the two blasts are described in the Quran in detail. A great deal else that is repeated about him is not established at all, and that is separated out at the bottom of this entry rather than mixed in with the rest.",
    detailAr: "هو الملَك الذي بعمله تنتهي الدنيا ثم تُبعث. اسمه ثابت، ووظيفته ثابتة، والنفختان مبسوطتان في القرآن. وكثيرٌ مما يُتداول عنه سوى ذلك غير ثابتٍ البتّة، وقد أُفرد في آخر هذا المدخل ولم يُخلط بالثابت.",
    arabic: "اللَّهُمَّ رَبَّ جِبْرِيلَ وَمِيكَائِيلَ وَإِسْرَافِيلَ، فَاطِرَ السَّمَاوَاتِ وَالْأَرْضِ",
    points: [
      { en: "HIS NAME IS ESTABLISHED. The Prophet ﷺ used to open his night prayer saying: O Allah, Lord of Jibril and Mika'il and Israfil, Originator of the heavens and the earth. That is in Sahih Muslim — so anyone who says the name Israfil is unfounded is mistaken.",
        ar: "اسمه ثابت. كان النبي ﷺ يفتتح صلاته من الليل بقوله: اللهم ربَّ جبريل وميكائيل وإسرافيل، فاطر السماوات والأرض. وهو في صحيح مسلم — فمن زعم أن اسم إسرافيل لا أصل له فقد وهم.",
        ref: "Sahih Muslim, Book of the Prayer of Travellers — Sahih" },
      { en: "THE FIRST BLAST KILLS EVERYTHING. And the Trumpet is blown, and whoever is in the heavens and whoever is on the earth falls dead — except whom Allah wills. Not some of them. Whoever is in them.",
        ar: "النفخة الأولى يموت بها كل شيء. ونُفخ في الصور فصعق من في السماوات ومن في الأرض إلا من شاء الله. لا بعضهم، بل من فيهنّ.",
        ref: "Surah Az-Zumar (39:68)" },
      { en: "THE SECOND BLAST BRINGS EVERYTHING BACK. Then it is blown again — and at once they are standing, looking on. One verse holds both: the end of everything, and the beginning of the accounting.",
        ar: "والنفخة الثانية يعود بها كل شيء. ثم نُفخ فيه أخرى فإذا هم قيامٌ ينظرون. آيةٌ واحدة جمعت الأمرين: فناء كل شيء، وابتداء الحساب.",
        ref: "Surah Az-Zumar (39:68)" },
      { en: "IT IS ONE SOUND, NOT A LONG EVENT. It will be but one shout, and at once they are all brought present before Us. And: they await only one shout, which will seize them while they are disputing — they will not be able to make a will, nor return to their families.",
        ar: "وهي صيحةٌ واحدة لا حدثٌ ممتدّ. إن كانت إلا صيحةً واحدةً فإذا هم جميعٌ لدينا محضرون. وقال: ما ينظرون إلا صيحةً واحدةً تأخذهم وهم يخصِّمون، فلا يستطيعون توصيةً ولا إلى أهلهم يرجعون.",
        ref: "Surah Ya-Sin (36:49-53)" },
      { en: "BETWEEN THE TWO BLASTS: FORTY. Abu Hurairah رضي الله عنه narrated: between the two blasts is forty. They asked: forty days? He said: I decline to say. Forty months? I decline. Forty years? I decline. Then Allah sends down water from the sky and they grow as vegetation grows.",
        ar: "وبين النفختين أربعون. قال أبو هريرة رضي الله عنه: ما بين النفختين أربعون. قيل: أربعون يومًا؟ قال: أبيتُ. قيل: أربعون شهرًا؟ قال: أبيتُ. قيل: أربعون سنة؟ قال: أبيتُ. ثم يُنزل الله من السماء ماءً فينبتون كما ينبت البقل.",
        ref: "Sahih al-Bukhari, Book of Tafsir, Hadith 4935 — Sahih, agreed upon" },
      { en: "AND ONE BONE DOES NOT DECAY. In the same hadith: there is nothing of a human being that does not decay, except one bone — the tailbone — and from it the creation is assembled on the Day of Resurrection.",
        ar: "وعظمٌ واحد لا يبلى. وفي الحديث نفسه: ليس من الإنسان شيءٌ إلا يبلى إلا عظمًا واحدًا وهو عَجْب الذَّنَب، ومنه يُركَّب الخلق يوم القيامة.",
        ref: "Sahih al-Bukhari, Book of Tafsir, Hadith 4935 — Sahih, agreed upon" },
      { en: "THE TRUMPET IS A HORN, AND ITS BEARER IS ALREADY WAITING. The Prophet ﷺ was asked what the Sur is and said: a horn that is blown into. And he said: how can I be at ease when the bearer of the Horn has already put it to his mouth, inclined his forehead and turned his ear, waiting to be told to blow? The companions said: what should we say? He said: say Allah is enough for us and He is the best Disposer of affairs. IMPORTANT: this one is narrated by at-Tirmidhi and Ahmad and graded authentic by al-Albani — it is NOT in al-Bukhari or Muslim, and the difference is stated here rather than blurred.",
        ar: "والصور قرنٌ يُنفخ فيه، وصاحبه قد استعدّ. سُئل النبي ﷺ عن الصور فقال: قرنٌ يُنفخ فيه. وقال: كيف أنعم وصاحب القرن قد التقم القرن وحنى جبهته وأصغى سمعه ينتظر أن يُؤمر أن ينفخ؟ قالوا: فما نقول؟ قال: قولوا حسبنا الله ونعم الوكيل. وتنبيه: هذا رواه الترمذي وأحمد وصحّحه الألباني، وليس في البخاري ولا مسلم، ونُبيّن الفرق ولا نُخفيه.",
        ref: "Jami' at-Tirmidhi and Musnad Ahmad, authenticated by al-Albani — outside the two Sahihs" },
      { en: "WHAT IS NOT ESTABLISHED ABOUT HIM. The descriptions people repeat of Israfil's eyes, his size, that he has not blinked since he was created, that his eyes are like stars — none of that is in the Quran or in the two Sahihs. Some of it comes from Israiliyyat. It is left out here for that reason, not because it is unknown.",
        ar: "وما لا يثبت عنه. ما يُتداول من وصف عيني إسرافيل وعِظَم خلقه، وأنه لم يطرف منذ خُلق، وأن عينيه كالكوكبين — ليس شيءٌ من ذلك في القرآن ولا في الصحيحين، وبعضه من الإسرائيليات. ولذلك تُرك هنا، لا لأنه مجهول.",
        ref: "Not found in the Quran or the two Sahihs" }
    ],
    ref: "Sahih Muslim, Book of the Prayer of Travellers (his name); Surah Az-Zumar (39:68) and Surah Ya-Sin (36:49-53) (the two blasts); Sahih al-Bukhari 4935 (the forty between them)",
    strength: "Sahih and Quran for everything above except where the entry says otherwise",
    keys: ["israfil", "trumpet", "sur", "blast", "horn", "end of the world", "resurrection", "two blasts", "sound",
           "إسرافيل", "الصور", "النفخة", "النفختان", "القرن", "الصيحة", "البعث", "عجب الذنب"]
  },
  {
    id: "ang-jibril-full",
    group: "named",
    order: 2,
    name: "Jibril — everything narrated about him, gathered",
    nameAr: "جبريل عليه السلام — ما ثبت عنه مجموعًا",
    role: "The angel of revelation",
    roleAr: "ملَك الوحي",
    detail: "More is authentically narrated about Jibril than about any other angel, because he is the one the Prophet ﷺ dealt with directly and repeatedly. What follows is that material gathered in one place.",
    detailAr: "ما ثبت عن جبريل أكثر مما ثبت عن غيره من الملائكة، لأنه الذي كان يباشر النبي ﷺ ويتكرر لقاؤه به. وهذا جمعٌ لذلك في موضعٍ واحد.",
    arabic: "قُلْ مَن كَانَ عَدُوًّا لِّجِبْرِيلَ فَإِنَّهُ نَزَّلَهُ عَلَىٰ قَلْبِكَ بِإِذْنِ اللَّهِ",
    points: [
      { en: "SIX HUNDRED WINGS. Ibn Mas'ud رضي الله عنه said the Prophet ﷺ saw Jibril with six hundred wings.",
        ar: "له ستمائة جناح. قال ابن مسعود رضي الله عنه: رأى النبي ﷺ جبريل له ستمائة جناح.",
        ref: "Sahih al-Bukhari, Book of the Beginning of Creation, Hadith 3232; also 4856 and 4857 — Sahih" },
      { en: "HIS CREATION FILLED THE HORIZON. Aishah رضي الله عنها reported that he saw Jibril in the form in which he was created, and his creation blocked what is between the horizon.",
        ar: "وخَلقه سادّ الأفق. روت عائشة رضي الله عنها أنه رأى جبريل في صورته التي خُلق عليها، وخَلقه سادٌّ ما بين الأفق.",
        ref: "Sahih al-Bukhari, Book of the Beginning of Creation, Hadith 3234 — Sahih" },
      { en: "HE CAME IN THE FORM OF A MAN. He came in the form of Dihyah al-Kalbi رضي الله عنه, a companion the people knew by sight. And he came once as a stranger in white with black hair, whom nobody recognised and who bore no marks of travel, sat knee to knee with the Prophet ﷺ and asked him about Islam, iman and ihsan — and when he left, the Prophet ﷺ said: that was Jibril, who came to teach you your religion.",
        ar: "وكان يأتي في صورة رجل. أتى في صورة دِحية الكلبي رضي الله عنه وكان الناس يعرفونه. وأتى مرةً كرجلٍ شديد بياض الثياب شديد سواد الشعر، لا يُعرف ولا يُرى عليه أثر السفر، فأسند ركبتيه إلى ركبتي النبي ﷺ وسأله عن الإسلام والإيمان والإحسان — فلما انصرف قال ﷺ: هذا جبريل أتاكم يعلّمكم دينكم.",
        ref: "Sahih al-Bukhari, Book of Faith, Hadith 50; and Sahih Muslim, Book of Faith — Sahih, agreed upon" },
      { en: "HE REVIEWED THE QURAN WITH HIM EVERY RAMADAN. Ibn Abbas رضي الله عنهما said the Prophet ﷺ was the most generous of people, and he was at his most generous in Ramadan when Jibril met him — and Jibril used to meet him every night of Ramadan and review the Quran with him.",
        ar: "وكان يعارضه القرآن كل رمضان. قال ابن عباس رضي الله عنهما: كان النبي ﷺ أجود الناس، وكان أجود ما يكون في رمضان حين يلقاه جبريل، وكان يلقاه في كل ليلةٍ من رمضان فيدارسه القرآن.",
        ref: "Sahih al-Bukhari, Book of the Beginning of Revelation, Hadith 6 — Sahih" },
      { en: "HE DOES NOT DESCEND OF HIS OWN ACCORD. The Quran gives his own words: we do not descend except by the command of your Lord. To Him belongs what is before us and what is behind us.",
        ar: "ولا ينزل من تلقاء نفسه. حكى القرآن قوله: وما نتنزّل إلا بأمر ربك، له ما بين أيدينا وما خلفنا.",
        ref: "Surah Maryam (19:64)" },
      { en: "AT TA'IF, HE OFFERED AND DID NOT INSIST. When the Prophet ﷺ was driven out and left grieving, he raised his head and found a cloud shading him, and Jibril in it, calling to him: Allah has heard what your people said to you, and has sent you the angel of the mountains, to command him what you wish.",
        ar: "وفي الطائف عرض ولم يُلحّ. لما أُخرج النبي ﷺ ومضى مهمومًا رفع رأسه فإذا سحابةٌ قد أظلّته، وفيها جبريل يناديه: إن الله قد سمع قول قومك لك وما ردّوا عليك، وقد بعث إليك ملَك الجبال لتأمره بما شئت فيهم.",
        ref: "Sahih al-Bukhari, Book of the Beginning of Creation, Hadith 3231 — Sahih, agreed upon" }
    ],
    ref: "Surah Al-Baqarah (2:97); Sahih al-Bukhari 3232, 3234, 50, 6, 3231; Sahih Muslim, Book of Faith",
    strength: "Sahih — Agreed upon (al-Bukhari and Muslim)",
    keys: ["jibril", "gabriel", "revelation", "wings", "dihyah", "hadith jibril", "ramadan",
           "جبريل", "الوحي", "ستمائة جناح", "دحية", "حديث جبريل", "معارضة القرآن"]
  },
  {
    id: "ang-mikail-full",
    group: "named",
    order: 3,
    name: "Mika'il — what is established, and what is only commonly said",
    nameAr: "ميكائيل — الثابت عنه وما يُقال ولا يثبت",
    role: "Named in the Quran and by the Prophet ﷺ",
    roleAr: "مُسمّى في القرآن وعلى لسان النبي ﷺ",
    detail: "Mika'il is named, but far less is narrated about him than about Jibril — and the job most people assign him is not from the two Sahihs. Both halves of that are stated here.",
    detailAr: "ميكائيل مُسمّى، لكن ما ثبت عنه أقلّ بكثير مما ثبت عن جبريل — والوظيفة التي ينسبها إليه أكثر الناس ليست من الصحيحين. ونذكر الأمرين معًا.",
    arabic: "مَن كَانَ عَدُوًّا لِّلَّهِ وَمَلَائِكَتِهِ وَرُسُلِهِ وَجِبْرِيلَ وَمِيكَالَ فَإِنَّ اللَّهَ عَدُوٌّ لِّلْكَافِرِينَ",
    points: [
      { en: "NAMED IN THE QURAN, alongside Jibril, in Al-Baqarah.",
        ar: "مُسمّى في القرآن مع جبريل في سورة البقرة.",
        ref: "Surah Al-Baqarah (2:98)" },
      { en: "NAMED BY THE PROPHET ﷺ in the supplication he opened the night prayer with, and in the narration where the two angels identify themselves: I am Jibril, and this is Mika'il.",
        ar: "وسمّاه النبي ﷺ في دعاء استفتاح قيام الليل، وفي الحديث الذي عرّف فيه الملَكان بنفسيهما: وأنا جبريل، وهذا ميكائيل.",
        ref: "Sahih Muslim, Book of the Prayer of Travellers; and Sahih al-Bukhari, Hadith 3236 — Sahih" },
      { en: "THE RAIN AND THE PROVISION. It is very widely said that Mika'il is charged with rain and with provision. That is reported in works of tafsir and in narrations from the companions and those after them — it is NOT in al-Bukhari or Muslim as a statement of the Prophet ﷺ. It is a well-known and widely accepted view, but it does not have the rank of the two Sahihs, and this page will not present it as though it did.",
        ar: "أما المطر والرزق فمشهورٌ جدًّا أن ميكائيل موكَّلٌ بهما، وقد ورد ذلك في كتب التفسير وفي آثارٍ عن الصحابة ومن بعدهم — وليس في البخاري ولا مسلم مرفوعًا إلى النبي ﷺ. وهو قولٌ مشهورٌ متلقًّى بالقبول، لكنه ليس في رتبة الصحيحين، ولا نُقدّمه هنا على أنه كذلك.",
        ref: "Reported in tafsir and in narrations from the companions and later — outside the two Sahihs" }
    ],
    ref: "Surah Al-Baqarah (2:98); Sahih al-Bukhari, Hadith 3236; Sahih Muslim, Book of the Prayer of Travellers",
    strength: "Quran and Sahih for the name; the rain and provision: outside the two Sahihs",
    keys: ["mikail", "michael", "rain", "provision", "rizq",
           "ميكائيل", "ميكال", "المطر", "الرزق"]
  },
  {
    id: "ang-malik-full",
    group: "named",
    order: 4,
    name: "Malik — the keeper of the Fire",
    nameAr: "مالك — خازن النار",
    role: "The angel in charge of the Fire",
    roleAr: "الملَك الموكَّل بالنار",
    detail: "Malik is named in the Quran, and the Prophet ﷺ was shown him. What the Quran records of him is a single exchange, and it is one of the heaviest passages in the whole book.",
    detailAr: "مالك مُسمّى في القرآن، وقد أُري النبي ﷺ إياه. وما سجّله القرآن عنه محاورةٌ واحدة، وهي من أثقل ما في الكتاب.",
    arabic: "وَنَادَوْا يَا مَالِكُ لِيَقْضِ عَلَيْنَا رَبُّكَ ۖ قَالَ إِنَّكُم مَّاكِثُونَ",
    points: [
      { en: "THEY CALL HIM BY NAME. Those inside the Fire call out: O Malik, let your Lord finish us off. They are not asking to be released — they are asking to be ended.",
        ar: "ينادونه باسمه. ينادي أهل النار: يا مالك ليقضِ علينا ربّك. وليسوا يطلبون الخروج، وإنما يطلبون الموت.",
        ref: "Surah Az-Zukhruf (43:77)" },
      { en: "AND HIS ANSWER IS THREE WORDS. He said: you are staying. The scholars of tafsir note that the answer does not come at once — and that it is the shortness of it that carries the weight.",
        ar: "وجوابه كلمتان. قال: إنكم ماكثون. ونبّه المفسّرون على أن الجواب لا يأتي سريعًا — وأن قِصَره هو موضع الثقل فيه.",
        ref: "Surah Az-Zukhruf (43:77)" },
      { en: "HE WAS SHOWN HIM ON THE NIGHT OF THE MI'RAJ. Ibn Abbas رضي الله عنهما: I was shown Musa, and Isa, and Malik the keeper of the Fire, and the Dajjal — among signs Allah showed him.",
        ar: "وأُريه ليلة المعراج. قال ابن عباس رضي الله عنهما: رأيت موسى وعيسى، ورأيت مالكًا خازن النار، والدجّال — في آياتٍ أراهنّ الله إياه.",
        ref: "Sahih al-Bukhari, Hadith 3239; and Sahih Muslim, Book of Faith — Sahih, agreed upon" },
      { en: "AND OVER THE FIRE, NINETEEN. Over it are nineteen — angels described as stern and severe, who do not disobey Allah in what He commands them, and who do exactly what they are commanded. The Zabaniyah are named in Surah Al-'Alaq.",
        ar: "وعليها تسعة عشر. عليها ملائكةٌ غلاظٌ شداد لا يعصون الله ما أمرهم ويفعلون ما يُؤمرون. والزبانية مُسمَّون في سورة العلق.",
        ref: "Surah Al-Muddaththir (74:30); Surah At-Tahrim (66:6); Surah Al-'Alaq (96:18)" }
    ],
    ref: "Surah Az-Zukhruf (43:77); Sahih al-Bukhari, Hadith 3239; Sahih Muslim, Book of Faith",
    strength: "Quran; and Sahih — Agreed upon (al-Bukhari and Muslim)",
    keys: ["malik", "keeper of fire", "hell", "zabaniyah", "nineteen",
           "مالك", "خازن النار", "الزبانية", "تسعة عشر", "النار"]
  },
  {
    id: "ang-death-full",
    group: "named",
    order: 5,
    name: "The Angel of Death — and why he has no name here",
    nameAr: "ملَك الموت — ولِمَ لا يُسمّى هنا",
    role: "Appointed to take the soul",
    roleAr: "الموكَّل بقبض الروح",
    detail: "The Quran describes him precisely and does not name him. What people call him is a later addition, and this page keeps the two apart.",
    detailAr: "وصفه القرآن وصفًا دقيقًا ولم يُسمِّه. وما يسمّيه الناس به زيادةٌ متأخرة، ونفرّق هنا بين الأمرين.",
    arabic: "قُلْ يَتَوَفَّاكُم مَّلَكُ الْمَوْتِ الَّذِي وُكِّلَ بِكُمْ ثُمَّ إِلَىٰ رَبِّكُمْ تُرْجَعُونَ",
    points: [
      { en: "HE IS PUT IN CHARGE — the wording is 'who has been put in charge of you'. It is an appointment, not an independent power.",
        ar: "هو موكَّل — واللفظ: «الذي وُكِّل بكم». فهي وكالةٌ لا سلطانٌ مستقلّ.",
        ref: "Surah As-Sajdah (32:11)" },
      { en: "AND THERE ARE OTHERS WITH HIM. The Quran also speaks in the plural: those whom the angels take in a good state, saying peace be upon you — enter Paradise for what you used to do.",
        ar: "ومعه غيره. وجاء القرآن بالجمع أيضًا: الذين تتوفّاهم الملائكة طيّبين يقولون سلامٌ عليكم ادخلوا الجنة بما كنتم تعملون.",
        ref: "Surah An-Nahl (16:32)" },
      { en: "AND FOR THE OTHER KIND, THE SAME ANGELS ARE DESCRIBED DIFFERENTLY: if you could see when the angels take those who disbelieved, striking their faces and their backs.",
        ar: "وفي الحال الأخرى وُصفوا بخلاف ذلك: ولو ترى إذ يتوفّى الذين كفروا الملائكة يضربون وجوههم وأدبارهم.",
        ref: "Surah Al-Anfal (8:50)" },
      { en: "THE NAME 'AZRAIL' IS NOT IN THE QURAN AND NOT IN THE TWO SAHIHS. Almost everyone uses it. It still is not established, and saying so is not a criticism of anyone.",
        ar: "واسم «عزرائيل» ليس في القرآن ولا في الصحيحين. ويستعمله عامة الناس، ومع ذلك فهو غير ثابت، وبيان ذلك ليس تخطئةً لأحد.",
        ref: "Not found in the Quran or the two Sahihs" }
    ],
    ref: "Surah As-Sajdah (32:11); Surah An-Nahl (16:32); Surah Al-Anfal (8:50)",
    strength: "Quran for the description; the name 'Azrail' is NOT established",
    keys: ["angel of death", "death", "soul", "azrail", "malak al mawt",
           "ملك الموت", "قبض الروح", "عزرائيل", "الوفاة"]
  },
  {
    id: "ang-mountains",
    group: "named",
    order: 6,
    name: "The angel of the mountains — the offer that was refused",
    nameAr: "ملَك الجبال — العرض الذي رُدّ",
    role: "Sent at Ta'if, and told no",
    roleAr: "بُعث يوم الطائف فرُدّ",
    detail: "Aishah رضي الله عنها asked the Prophet ﷺ whether any day had been harder on him than Uhud. He described the day of al-Aqabah, when he offered himself to Ibn Abd Yalil and was refused, and left grieving without knowing where he was going until he found himself at Qarn ath-Tha'alib. This is the angel who came then — and what the Prophet ﷺ said to him is the reason so much of the world is Muslim today.",
    detailAr: "سألت عائشة رضي الله عنها النبي ﷺ: هل أتى عليك يومٌ كان أشدّ من يوم أُحد؟ فذكر يوم العقبة، حين عرض نفسه على ابن عبد ياليل فلم يُجَب، فانطلق مهمومًا لا يدري أين يمضي حتى أفاق بقَرْن الثعالب. وهذا هو الملَك الذي جاءه حينئذ — وما قاله له النبي ﷺ هو سبب إسلام من أسلم من أهل الأرض بعده.",
    arabic: "إِنْ شِئْتَ أَنْ أُطْبِقَ عَلَيْهِمُ الْأَخْشَبَيْنِ … بَلْ أَرْجُو أَنْ يُخْرِجَ اللَّهُ مِنْ أَصْلَابِهِمْ مَنْ يَعْبُدُ اللَّهَ وَحْدَهُ لَا يُشْرِكُ بِهِ شَيْئًا",
    points: [
      { en: "JIBRIL CALLED FIRST: Allah has heard what your people said to you and how they answered you, and has sent you the angel of the mountains, to command him what you wish.",
        ar: "ناداه جبريل أولًا: إن الله قد سمع قول قومك لك وما ردّوا عليك، وقد بعث إليك ملَك الجبال لتأمره بما شئت فيهم.",
        ref: "Sahih al-Bukhari, Book of the Beginning of Creation, Hadith 3231 — Sahih, agreed upon" },
      { en: "THEN THE ANGEL GREETED HIM AND OFFERED: O Muhammad — if you wish, I will bring the two mountains down upon them.",
        ar: "ثم سلّم عليه ملَك الجبال وعرض: يا محمد، إن شئت أن أُطبق عليهم الأخشبين.",
        ref: "Sahih al-Bukhari, Hadith 3231 — Sahih, agreed upon" },
      { en: "AND HE SAID NO. Rather, I hope that Allah will bring out from their loins those who worship Allah alone and associate nothing with Him. He was bleeding, he had been refused and driven out, the power to destroy them was placed in his hands — and he asked instead for their children.",
        ar: "فقال: لا. بل أرجو أن يُخرج الله من أصلابهم من يعبد الله وحده لا يشرك به شيئًا. وقد أُدمي وطُرد ورُدّ، ووُضعت قدرة إهلاكهم بين يديه — فسأل لأبنائهم لا عليهم.",
        ref: "Sahih al-Bukhari, Hadith 3231 — Sahih, agreed upon" }
    ],
    ref: "Sahih al-Bukhari, Book of the Beginning of Creation, Hadith 3231; and Sahih Muslim, Book of Jihad",
    strength: "Sahih — Agreed upon (al-Bukhari and Muslim)",
    keys: ["angel of mountains", "taif", "akhshabayn", "mercy", "rejected",
           "ملك الجبال", "الطائف", "الأخشبين", "قرن الثعالب"]
  },

  /* ================= THE MI'RAJ ================= */
  {
    id: "ang-jibril-miraj",
    group: "miraj",
    order: 1,
    name: "Jibril — who came for him, and stayed the whole way",
    nameAr: "جبريل — الذي جاءه وصحبه الطريق كلَّه",
    role: "The companion of the journey",
    roleAr: "رفيق الرحلة",
    detail: "It began before the journey did. Jibril came down, opened his chest, washed it with the water of Zamzam, brought a golden basin filled with wisdom and faith and emptied it into his chest, then closed it. Then he took him by the hand and ascended with him. At each of the seven heavens it was Jibril who asked for the gate, and Jibril whom he asked about anything he did not recognise.",
    detailAr: "بدأ الأمر قبل الرحلة نفسها. نزل جبريل ففرج صدره، وغسله بماء زمزم، وجاء بطستٍ من ذهبٍ مملوءٍ حكمةً وإيمانًا فأفرغه في صدره ثم أطبقه. ثم أخذ بيده فعرج به. وفي كل سماءٍ من السبع كان جبريل هو الذي يستفتح، وهو الذي يسأله عمّا لم يعرفه.",
    arabic: "فَنَزَلَ جِبْرِيلُ فَفَرَجَ صَدْرِي، ثُمَّ غَسَلَهُ بِمَاءِ زَمْزَمَ، ثُمَّ جَاءَ بِطَسْتٍ مِنْ ذَهَبٍ مُمْتَلِئٍ حِكْمَةً وَإِيمَانًا، فَأَفْرَغَهُ فِي صَدْرِي ثُمَّ أَطْبَقَهُ",
    points: [],
    ref: "Sahih al-Bukhari, Book of Prayer, Hadith 349 — narrated by Abu Dharr رضي الله عنه",
    strength: "Sahih — Narrated by al-Bukhari",
    keys: ["jibril", "miraj", "isra", "night journey", "chest", "zamzam",
           "جبريل", "المعراج", "الإسراء", "شق الصدر", "زمزم"]
  },
  {
    id: "ang-gatekeeper",
    group: "miraj",
    order: 2,
    name: "The keeper of each heaven — the same words at all seven gates",
    nameAr: "خازن كل سماء — الكلام نفسه عند الأبواب السبعة",
    role: "The angel appointed to the gate of each heaven",
    roleAr: "الملَك الموكَّل بباب كل سماء",
    detail: "The exchange happened seven times, at seven gates, with seven keepers: Jibril says open; the keeper asks who is this; he says Jibril; the keeper asks is anyone with you; he says Muhammad; the keeper asks has he been sent for; he says yes — and only then is it opened, and the greeting comes back: welcome to him, and what an excellent arrival.",
    detailAr: "تكرّر الحوار سبع مرات، عند سبعة أبواب، مع سبعة خزنة: يقول جبريل: افتح. فيقول الخازن: من هذا؟ فيقول: جبريل. فيقول: ومن معك؟ فيقول: محمد. فيقول: أوقد أُرسل إليه؟ فيقول: نعم. فعندها يُفتح، ويأتي الترحيب: مرحبًا به، ولنِعم المجيء جاء.",
    arabic: "قَالَ جِبْرِيلُ لِخَازِنِ السَّمَاءِ: افْتَحْ. قَالَ: مَنْ هَذَا؟ قَالَ: هَذَا جِبْرِيلُ. قَالَ: هَلْ مَعَكَ أَحَدٌ؟ قَالَ: نَعَمْ مَعِي مُحَمَّدٌ ﷺ. فَقَالَ: أُرْسِلَ إِلَيْهِ؟ قَالَ: نَعَمْ",
    points: [],
    ref: "Sahih al-Bukhari, Book of Prayer, Hadith 349; and Hadith 3207",
    strength: "Sahih — Narrated by al-Bukhari",
    keys: ["gatekeeper", "keeper of heaven", "seven heavens", "gate",
           "خازن السماء", "أبواب السماء", "السماوات السبع", "استفتح"]
  },
  {
    id: "ang-bayt-mamur",
    group: "miraj",
    order: 3,
    name: "The seventy thousand of al-Bayt al-Ma'mur",
    nameAr: "سبعون ألفًا في البيت المعمور",
    role: "The angels of the House that is visited",
    roleAr: "ملائكة البيت المعمور",
    detail: "In the seventh heaven, after meeting Ibrahim عليه السلام, al-Bayt al-Ma'mur was raised for him. He asked Jibril what it was: seventy thousand angels pray in it every day — and when they leave it, they never return to it again. A new seventy thousand, every day, since it began.",
    detailAr: "في السماء السابعة، بعد لقاء إبراهيم عليه السلام، رُفع له البيت المعمور، فسأل جبريل عنه فقال: يصلي فيه كل يومٍ سبعون ألف ملَك، إذا خرجوا منه لم يعودوا إليه آخر ما عليهم. سبعون ألفًا جددًا كل يوم، منذ كان.",
    arabic: "هَذَا الْبَيْتُ الْمَعْمُورُ يُصَلِّي فِيهِ كُلَّ يَوْمٍ سَبْعُونَ أَلْفَ مَلَكٍ، إِذَا خَرَجُوا لَمْ يَعُودُوا إِلَيْهِ آخِرَ مَا عَلَيْهِمْ",
    points: [],
    ref: "Sahih al-Bukhari, Book of the Beginning of Creation, Hadith 3207",
    strength: "Sahih — Narrated by al-Bukhari",
    keys: ["bayt al mamur", "seventy thousand", "seventh heaven", "how many angels",
           "البيت المعمور", "سبعون ألف ملك", "السماء السابعة", "عدد الملائكة"]
  },
  {
    id: "ang-pens",
    group: "miraj",
    order: 4,
    name: "The level where he heard the pens writing",
    nameAr: "المستوى الذي سمع فيه صريف الأقلام",
    role: "What is heard above the seventh heaven",
    roleAr: "ما يُسمع فوق السماء السابعة",
    detail: "He was raised until he reached a level at which he could hear the scratching of the pens. The scholars explain it as the writing of what Allah decrees. One line in the hadith, and it says a great deal: the decree is not silent — it is being written, and he was brought close enough to hear it.",
    detailAr: "عُرج به حتى ظهر لمستوًى يسمع فيه صريف الأقلام. وفسّره أهل العلم بكتابة ما يقضي الله به. سطرٌ واحد، وفيه معنًى عظيم: أن القدر لا يجري صامتًا بل يُكتب، وقد قُرِّب حتى سمع ذلك.",
    arabic: "ثُمَّ عُرِجَ بِي حَتَّى ظَهَرْتُ لِمُسْتَوًى أَسْمَعُ فِيهِ صَرِيفَ الْأَقْلَامِ",
    points: [],
    ref: "Sahih al-Bukhari, Book of Prayer, Hadith 349",
    strength: "Sahih — Narrated by al-Bukhari",
    keys: ["pens", "decree", "writing", "miraj",
           "صريف الأقلام", "القدر", "الكتابة", "المعراج"]
  },
  {
    id: "ang-adam-souls",
    group: "miraj",
    order: 5,
    name: "Adam, and the souls on his right and his left",
    nameAr: "آدم والأسودة عن يمينه وشماله",
    role: "What he saw at the gate of the lowest heaven",
    roleAr: "ما رآه عند باب السماء الدنيا",
    detail: "A man seated, with dark shapes on his right and dark shapes on his left. When he looked right he laughed, and when he looked left he wept. Jibril said: this is Adam, and these shapes are the souls of his children — those on the right are the people of Paradise, and those on the left are the people of the Fire.",
    detailAr: "رجلٌ قاعد، عن يمينه أسودةٌ وعن شماله أسودة، إذا نظر قِبَل يمينه ضحك، وإذا نظر قِبَل شماله بكى. فقال جبريل: هذا آدم، وهذه الأسودة نَسَم بنيه — فأهل اليمين أهل الجنة، والذين عن شماله أهل النار.",
    arabic: "هَذَا آدَمُ، وَهَذِهِ الْأَسْوِدَةُ عَنْ يَمِينِهِ وَشِمَالِهِ نَسَمُ بَنِيهِ، فَأَهْلُ الْيَمِينِ مِنْهُمْ أَهْلُ الْجَنَّةِ، وَالْأَسْوِدَةُ الَّتِي عَنْ شِمَالِهِ أَهْلُ النَّارِ",
    points: [],
    ref: "Sahih al-Bukhari, Book of Prayer, Hadith 349",
    strength: "Sahih — Narrated by al-Bukhari",
    keys: ["adam", "souls", "right and left", "first heaven",
           "آدم", "نسم بنيه", "اليمين والشمال", "السماء الدنيا"]
  },

  /* ================= NAMED / DESCRIBED IN THE QURAN ================= */
  {
    id: "ang-q-harut",
    group: "quran",
    order: 10,
    name: "Harut and Marut — the two at Babylon",
    nameAr: "هاروت وماروت — المَلَكان ببابل",
    role: "Two angels named in the Quran, sent as a trial",
    roleAr: "ملَكان مُسمَّيان، أُنزلا فتنة",
    detail: "The Quran names them in the account of what was taught at Babylon, and states that they would not teach anyone until they had said plainly: we are only a trial, so do not disbelieve. Besides Jibril and Mika'il, these are the only angels the Quran names.",
    detailAr: "سمّاهما القرآن في خبر ما أُنزل ببابل، وذكر أنهما لا يعلّمان أحدًا حتى يقولا: إنما نحن فتنةٌ فلا تكفر. وسوى جبريل وميكائيل لم يُسمِّ القرآن من الملائكة غيرهما.",
    arabic: "وَمَا أُنزِلَ عَلَى الْمَلَكَيْنِ بِبَابِلَ هَارُوتَ وَمَارُوتَ ۚ وَمَا يُعَلِّمَانِ مِنْ أَحَدٍ حَتَّىٰ يَقُولَا إِنَّمَا نَحْنُ فِتْنَةٌ فَلَا تَكْفُرْ",
    points: [],
    ref: "Surah Al-Baqarah (2:102)",
    strength: "Quran",
    keys: ["harut", "marut", "babylon", "magic", "sihr",
           "هاروت", "ماروت", "بابل", "السحر"]
  },
  {
    id: "ang-q-throne",
    group: "quran",
    order: 11,
    name: "The bearers of the Throne — eight on that Day",
    nameAr: "حملة العرش — ثمانية يومئذٍ",
    role: "Those who bear the Throne",
    roleAr: "الحاملون للعرش",
    detail: "And the angels will be on its edges, and eight will bear the Throne of your Lord above them on that Day. The Quran gives the number for that Day specifically. The descriptions of their size that circulate — the distance between the earlobe and the shoulder of one of them being a journey of seven hundred years — come from a narration of Abu Dawud, outside the two Sahihs.",
    detailAr: "والملَك على أرجائها، ويحمل عرش ربّك فوقهم يومئذٍ ثمانية. وذكر القرآن العدد في ذلك اليوم خاصةً. وأما ما يُتداول من وصف عِظَمهم — كأن ما بين شحمة أذن أحدهم وعاتقه مسيرة سبعمائة عام — فمن رواية أبي داود، وهي خارج الصحيحين.",
    arabic: "وَالْمَلَكُ عَلَىٰ أَرْجَائِهَا ۚ وَيَحْمِلُ عَرْشَ رَبِّكَ فَوْقَهُمْ يَوْمَئِذٍ ثَمَانِيَةٌ",
    points: [],
    ref: "Surah Al-Haqqah (69:17). The description of their size: Sunan Abu Dawud — outside the two Sahihs",
    strength: "Quran; the size description is outside the two Sahihs",
    keys: ["throne", "bearers", "eight", "arsh", "size",
           "حملة العرش", "ثمانية", "العرش", "عظم الخلق"]
  },
  {
    id: "ang-q-writers",
    group: "quran",
    order: 12,
    name: "The two writers — and the one ready beside you",
    nameAr: "الكاتبان — والرقيب العتيد",
    role: "The recording angels",
    roleAr: "الملائكة الكاتبون",
    detail: "Over you are keepers — noble, recording — who know whatever you do. And in Surah Qaf: not a word is uttered but that there is an observer beside him, ready. Two verses, and between them the whole idea that nothing said or done is unattended.",
    detailAr: "وإنّ عليكم لحافظين، كرامًا كاتبين، يعلمون ما تفعلون. وفي سورة ق: ما يلفظ من قولٍ إلا لديه رقيبٌ عتيد. آيتان، وفيهما المعنى كله: أن ما يُقال وما يُفعل لا يمرّ بغير حافظ.",
    arabic: "وَإِنَّ عَلَيْكُمْ لَحَافِظِينَ ۝ كِرَامًا كَاتِبِينَ ۝ يَعْلَمُونَ مَا تَفْعَلُونَ",
    points: [],
    ref: "Surah Al-Infitar (82:10-12); and Surah Qaf (50:18)",
    strength: "Quran",
    keys: ["writers", "kiraman katibin", "recording", "raqib atid",
           "الكاتبان", "كراما كاتبين", "رقيب عتيد", "كتابة الأعمال"]
  },
  {
    id: "ang-q-badr",
    group: "quran",
    order: 13,
    name: "The angels sent down at Badr",
    nameAr: "الملائكة المُنزَلون يوم بدر",
    role: "Sent as reinforcement, and as reassurance",
    roleAr: "أُنزلوا مددًا وبشرى",
    detail: "Allah says He reinforced them with a thousand angels in succession — and then says why: He made it only as good news, and so that hearts would be at rest by it. Victory is from Allah alone, not from the number. In Al-Imran the figure is three thousand, then five thousand marked.",
    detailAr: "أخبر الله أنه أمدّهم بألفٍ من الملائكة مردفين، ثم بيّن العلة: وما جعله الله إلا بشرى ولتطمئنّ به قلوبكم. فالنصر من عند الله وحده لا من العدد. وفي آل عمران ثلاثة آلاف ثم خمسة آلاف مسوّمين.",
    arabic: "إِذْ تَسْتَغِيثُونَ رَبَّكُمْ فَاسْتَجَابَ لَكُمْ أَنِّي مُمِدُّكُم بِأَلْفٍ مِّنَ الْمَلَائِكَةِ مُرْدِفِينَ",
    points: [],
    ref: "Surah Al-Anfal (8:9-10); Surah Al-Imran (3:124-125)",
    strength: "Quran",
    keys: ["badr", "battle", "angels help", "victory",
           "بدر", "المدد", "الملائكة في بدر", "النصر"]
  },
  {
    id: "ang-q-guests",
    group: "quran",
    order: 14,
    name: "The messengers who came to Ibrahim and to Lut",
    nameAr: "الرسل الذين جاءوا إبراهيم ولوطًا",
    role: "Angels who came in the form of men",
    roleAr: "ملائكةٌ جاءوا في صورة رجال",
    detail: "They came to Ibrahim عليه السلام as guests. He did not know them, brought them a roasted calf, and when he saw their hands did not reach for it he became uneasy of them — and they told him not to fear, and gave his wife the news of Ishaq. Then they went on to the people of Lut. The Quran shows angels here in a form that was not recognised until they said who they were.",
    detailAr: "جاءوا إبراهيم عليه السلام أضيافًا فلم يعرفهم، فقرّب إليهم عجلًا حنيذًا، فلما رأى أيديهم لا تصل إليه نكرهم وأوجس منهم خيفة — فقالوا: لا تخف، وبشّروا امرأته بإسحاق. ثم مضوا إلى قوم لوط. فالقرآن يُري الملائكة هنا في صورةٍ لم تُعرف حتى أخبروا عن أنفسهم.",
    arabic: "فَلَمَّا رَأَىٰ أَيْدِيَهُمْ لَا تَصِلُ إِلَيْهِ نَكِرَهُمْ وَأَوْجَسَ مِنْهُمْ خِيفَةً ۚ قَالُوا لَا تَخَفْ إِنَّا أُرْسِلْنَا إِلَىٰ قَوْمِ لُوطٍ",
    points: [],
    ref: "Surah Hud (11:69-81); Surah Adh-Dhariyat (51:24-30)",
    strength: "Quran",
    keys: ["ibrahim", "lut", "guests", "angels as men", "calf",
           "إبراهيم", "لوط", "الضيف", "العجل"]
  },
  {
    id: "ang-q-maryam",
    group: "quran",
    order: 15,
    name: "The one who came to Maryam",
    nameAr: "الذي أتى مريم عليها السلام",
    role: "Sent to her as a perfect man",
    roleAr: "تمثّل لها بشرًا سويًّا",
    detail: "We sent to her Our spirit, and he appeared to her as a well-proportioned man. She said: I seek refuge in the Most Merciful from you, if you fear Allah. He said: I am only a messenger of your Lord, to give you a pure boy.",
    detailAr: "فأرسلنا إليها روحنا فتمثّل لها بشرًا سويًّا. قالت: إني أعوذ بالرحمن منك إن كنت تقيًّا. قال: إنما أنا رسول ربّك لأهب لك غلامًا زكيًّا.",
    arabic: "فَأَرْسَلْنَا إِلَيْهَا رُوحَنَا فَتَمَثَّلَ لَهَا بَشَرًا سَوِيًّا ۝ قَالَتْ إِنِّي أَعُوذُ بِالرَّحْمَٰنِ مِنكَ إِن كُنتَ تَقِيًّا",
    points: [],
    ref: "Surah Maryam (19:17-19)",
    strength: "Quran",
    keys: ["maryam", "mary", "isa", "ruh",
           "مريم", "الروح", "بشارة عيسى"]
  },
  {
    id: "ang-q-qadr",
    group: "quran",
    order: 16,
    name: "The angels who descend on the Night of Decree",
    nameAr: "الملائكة الذين يتنزّلون ليلة القدر",
    role: "Descending with every matter",
    roleAr: "يتنزّلون بكل أمر",
    detail: "The angels and the Spirit descend in it by permission of their Lord for every matter. Peace it is, until the emergence of dawn.",
    detailAr: "تنزّل الملائكة والروح فيها بإذن ربهم من كل أمر. سلامٌ هي حتى مطلع الفجر.",
    arabic: "تَنَزَّلُ الْمَلَائِكَةُ وَالرُّوحُ فِيهَا بِإِذْنِ رَبِّهِم مِّن كُلِّ أَمْرٍ ۝ سَلَامٌ هِيَ حَتَّىٰ مَطْلَعِ الْفَجْرِ",
    points: [],
    ref: "Surah Al-Qadr (97:4-5)",
    strength: "Quran",
    keys: ["laylat al qadr", "night of decree", "ramadan",
           "ليلة القدر", "تنزل الملائكة", "رمضان"]
  },

  /* ================= AROUND YOU EVERY DAY ================= */
  {
    id: "ang-created-from",
    group: "sahih",
    order: 20,
    name: "What they were created from",
    nameAr: "مِمَّ خُلقوا",
    role: "Their origin, in one sentence",
    roleAr: "أصل خِلقتهم في جملة",
    detail: "The angels were created from light, and the jinn were created from a smokeless flame, and Adam was created from what you have been told about. One hadith, and it settles the question people ask most.",
    detailAr: "خُلقت الملائكة من نور، وخُلق الجانّ من مارجٍ من نار، وخُلق آدم مما وُصف لكم. حديثٌ واحد فيه جواب أكثر ما يُسأل عنه.",
    arabic: "خُلِقَتِ الْمَلَائِكَةُ مِنْ نُورٍ، وَخُلِقَ الْجَانُّ مِنْ مَارِجٍ مِنْ نَارٍ، وَخُلِقَ آدَمُ مِمَّا وُصِفَ لَكُمْ",
    points: [],
    ref: "Sahih Muslim, Book of Asceticism — narrated by Aishah رضي الله عنها",
    strength: "Sahih — Narrated by Muslim",
    keys: ["created from light", "what are angels made of", "noor", "jinn",
           "خلقت الملائكة من نور", "خلق الملائكة", "الجن", "النور"]
  },
  {
    id: "ang-shifts",
    group: "sahih",
    order: 21,
    name: "The two shifts that change over you at Fajr and Asr",
    nameAr: "الملائكة يتعاقبون فيكم بالليل والنهار",
    role: "Two shifts, meeting twice a day",
    roleAr: "فوجان يجتمعان مرتين في اليوم",
    detail: "Angels take turns among you by night and by day, and they gather at the prayer of Fajr and the prayer of Asr. Then those who spent the night among you ascend, and their Lord asks them — though He knows best — how did you leave My servants? They say: we left them praying, and we came to them praying.",
    detailAr: "يتعاقبون فيكم ملائكةٌ بالليل وملائكةٌ بالنهار، ويجتمعون في صلاة الفجر وصلاة العصر. ثم يعرج الذين باتوا فيكم فيسألهم ربّهم وهو أعلم بهم: كيف تركتم عبادي؟ فيقولون: تركناهم وهم يصلّون، وأتيناهم وهم يصلّون.",
    arabic: "يَتَعَاقَبُونَ فِيكُمْ مَلَائِكَةٌ بِاللَّيْلِ وَمَلَائِكَةٌ بِالنَّهَارِ، وَيَجْتَمِعُونَ فِي صَلَاةِ الْفَجْرِ وَصَلَاةِ الْعَصْرِ",
    points: [],
    ref: "Sahih al-Bukhari, Book of the Times of Prayer, Hadith 555 — Sahih, agreed upon",
    strength: "Sahih — Agreed upon (al-Bukhari and Muslim)",
    keys: ["shifts", "fajr", "asr", "angels watching",
           "يتعاقبون", "ملائكة الليل والنهار", "الفجر والعصر"]
  },
  {
    id: "ang-dhikr-search",
    group: "sahih",
    order: 22,
    name: "The angels who go looking for people remembering Allah",
    nameAr: "الملائكة الذين يلتمسون أهل الذكر",
    role: "Roaming, searching, and then reporting",
    roleAr: "يطوفون ويلتمسون ثم يرفعون الخبر",
    detail: "Allah has angels who roam the roads seeking out the people of remembrance. When they find a people remembering Allah they call to one another: come to what you were looking for — and they cover them with their wings up to the lowest heaven. Then their Lord asks them, though He knows best, what My servants are saying. And at the end of it He says: I call you to witness that I have forgiven them. One of the angels says: among them is so-and-so, he is not one of them, he only came for something he needed. He says: they are a people whose sitting companion is not made wretched.",
    detailAr: "إن لله ملائكةً يطوفون في الطرق يلتمسون أهل الذكر، فإذا وجدوا قومًا يذكرون الله تنادوا: هلمّوا إلى حاجتكم — فيحفّونهم بأجنحتهم إلى السماء الدنيا. ثم يسألهم ربّهم وهو أعلم: ما يقول عبادي؟ وفي آخره يقول: أُشهدكم أني قد غفرت لهم. فيقول ملَكٌ منهم: فيهم فلانٌ ليس منهم، إنما جاء لحاجة. فيقول: هم القوم لا يشقى بهم جليسهم.",
    arabic: "إِنَّ لِلَّهِ مَلَائِكَةً يَطُوفُونَ فِي الطُّرُقِ يَلْتَمِسُونَ أَهْلَ الذِّكْرِ … هُمُ الْقَوْمُ لَا يَشْقَىٰ بِهِمْ جَلِيسُهُمْ",
    points: [],
    ref: "Sahih al-Bukhari, Book of Supplications, Hadith 6408 — Sahih",
    strength: "Sahih — Narrated by al-Bukhari",
    keys: ["dhikr", "circles", "gatherings", "remembrance", "forgiven",
           "الذكر", "حلق الذكر", "الملائكة", "المغفرة", "لا يشقى جليسهم"]
  },
  {
    id: "ang-dhikr-surround",
    group: "sahih",
    order: 23,
    name: "What comes down on a gathering of remembrance",
    nameAr: "ما ينزل على مجلس الذكر",
    role: "Four things, in one sentence",
    roleAr: "أربعة أمورٍ في جملةٍ واحدة",
    detail: "No people sit remembering Allah but that the angels surround them, mercy covers them, tranquillity descends upon them, and Allah mentions them among those with Him. Four things at once, and the angels are only the first of them.",
    detailAr: "لا يقعد قومٌ يذكرون الله إلا حفّتهم الملائكة، وغشيتهم الرحمة، ونزلت عليهم السكينة، وذكرهم الله فيمن عنده. أربعةٌ معًا، والملائكة أولها لا كلّها.",
    arabic: "لَا يَقْعُدُ قَوْمٌ يَذْكُرُونَ اللَّهَ عَزَّ وَجَلَّ إِلَّا حَفَّتْهُمُ الْمَلَائِكَةُ، وَغَشِيَتْهُمُ الرَّحْمَةُ، وَنَزَلَتْ عَلَيْهِمُ السَّكِينَةُ، وَذَكَرَهُمُ اللَّهُ فِيمَنْ عِنْدَهُ",
    points: [],
    ref: "Sahih Muslim, Book of Remembrance and Supplication — narrated by Abu Hurairah and Abu Sa'id al-Khudri رضي الله عنهما",
    strength: "Sahih — Narrated by Muslim",
    keys: ["gathering", "sakinah", "mercy", "dhikr circle",
           "مجلس الذكر", "السكينة", "الرحمة", "حفتهم الملائكة"]
  },
  {
    id: "ang-in-your-place",
    group: "sahih",
    order: 24,
    name: "They ask forgiveness for you where you prayed",
    nameAr: "الملائكة تُصلّي عليك في مُصلّاك",
    role: "For as long as you stay sitting",
    roleAr: "ما دمت في مكانك",
    detail: "The angels send blessings on one of you as long as he remains where he prayed, so long as he does not break his wudu. They say: O Allah, forgive him. O Allah, have mercy on him.",
    detailAr: "الملائكة تصلّي على أحدكم ما دام في مُصلّاه الذي صلّى فيه ما لم يُحدِث، تقول: اللهم اغفر له، اللهم ارحمه.",
    arabic: "الْمَلَائِكَةُ تُصَلِّي عَلَىٰ أَحَدِكُمْ مَا دَامَ فِي مُصَلَّاهُ الَّذِي صَلَّى فِيهِ مَا لَمْ يُحْدِثْ، تَقُولُ: اللَّهُمَّ اغْفِرْ لَهُ، اللَّهُمَّ ارْحَمْهُ",
    points: [],
    ref: "Sahih al-Bukhari, Book of Prayer, Hadith 445 — Sahih, agreed upon",
    strength: "Sahih — Agreed upon (al-Bukhari and Muslim)",
    keys: ["after prayer", "sitting", "forgiveness", "musalla",
           "الملائكة تصلي عليه", "المصلى", "بعد الصلاة"]
  },
  {
    id: "ang-house",
    group: "sahih",
    order: 25,
    name: "The house they do not enter",
    nameAr: "البيت الذي لا تدخله الملائكة",
    role: "What keeps them out",
    roleAr: "ما يمنعهم من الدخول",
    detail: "The angels do not enter a house in which there is a dog or images. Scholars discussed at length what falls under 'images' and what a working dog changes, and this page does not settle that — but the hadith itself is short and agreed upon.",
    detailAr: "لا تدخل الملائكة بيتًا فيه كلبٌ ولا صورة تماثيل. وقد بسط أهل العلم الكلام في ما يدخل في «الصور» وفي كلب الحاجة، ولا تفصل هذه الصفحة في ذلك — وأما الحديث نفسه فقصيرٌ متفقٌ عليه.",
    arabic: "لَا تَدْخُلُ الْمَلَائِكَةُ بَيْتًا فِيهِ كَلْبٌ وَلَا صُورَةُ تَمَاثِيلَ",
    points: [],
    ref: "Sahih al-Bukhari, Book of the Beginning of Creation, Hadith 3225 — Sahih, agreed upon",
    strength: "Sahih — Agreed upon (al-Bukhari and Muslim)",
    keys: ["dog", "images", "pictures", "house", "statues",
           "الكلب", "الصور", "التماثيل", "البيت"]
  },

  /* ================= FAMOUS BUT NOT ESTABLISHED ================= */
  {
    id: "ang-not-azrail",
    group: "notest",
    order: 40,
    name: "'Azrail' — not in the Quran, not in the two Sahihs",
    nameAr: "«عزرائيل» — ليس في القرآن ولا الصحيحين",
    role: "A name in wide circulation with no authentic source",
    roleAr: "اسمٌ منتشرٌ لا أصل له في الصحيحين",
    detail: "The Quran calls him Malak al-Mawt — the Angel of Death — and gives him no personal name. The name Azrail, which almost everyone uses, is in neither the Quran nor al-Bukhari nor Muslim.",
    detailAr: "سمّاه القرآن «ملَك الموت» ولم يُعطه اسمًا علَمًا. وأما «عزرائيل» الذي يستعمله عامة الناس فليس في القرآن ولا في البخاري ومسلم.",
    arabic: "قُلْ يَتَوَفَّاكُم مَّلَكُ الْمَوْتِ الَّذِي وُكِّلَ بِكُمْ",
    points: [],
    ref: "Surah As-Sajdah (32:11) for the description. The name: not found in the Quran or the two Sahihs",
    strength: "The description is Quran. The NAME is not established",
    keys: ["azrail", "azrael", "angel of death name",
           "عزرائيل", "اسم ملك الموت"]
  },
  {
    id: "ang-not-ridwan",
    group: "notest",
    order: 41,
    name: "'Ridwan' — the keeper of Paradise is not named",
    nameAr: "«رِضوان» — خازن الجنة غير مُسمّى",
    role: "The Quran calls them khazanatuha — its keepers",
    roleAr: "سمّاهم القرآن «خزنتها»",
    detail: "The Quran records what the keepers of Paradise say to those arriving: peace be upon you, you have done well, so enter it to remain forever. It calls them its keepers and names none of them Ridwan.",
    detailAr: "ذكر القرآن ما تقوله خزنة الجنة للقادمين: سلامٌ عليكم طبتم فادخلوها خالدين. وسمّاهم «خزنتها» ولم يُسمِّ أحدهم رِضوان.",
    arabic: "وَقَالَ لَهُمْ خَزَنَتُهَا سَلَامٌ عَلَيْكُمْ طِبْتُمْ فَادْخُلُوهَا خَالِدِينَ",
    points: [],
    ref: "Surah Az-Zumar (39:73). The name: not found in the Quran or the two Sahihs",
    strength: "The description is Quran. The NAME is not established",
    keys: ["ridwan", "keeper of paradise",
           "رضوان", "خازن الجنة", "خزنة الجنة"]
  },
  {
    id: "ang-not-munkar",
    group: "notest",
    order: 42,
    name: "'Munkar and Nakir' — outside the two Sahihs, not baseless",
    nameAr: "«منكر ونكير» — خارج الصحيحين ولا يُقال لا أصل له",
    role: "The two angels of the questioning in the grave",
    roleAr: "ملَكا السؤال في القبر",
    detail: "The questioning in the grave itself is firmly established in the two Sahihs. The two NAMES come from a narration of at-Tirmidhi — outside al-Bukhari and Muslim, but not baseless. This sits between the established and the unfounded, and is marked that way rather than pushed to either side.",
    detailAr: "أما السؤال في القبر فثابتٌ في الصحيحين. وأما الاسمان فمن رواية الترمذي — خارج البخاري ومسلم، ولا يُقال لا أصل له. فهو بين الثابت والمردود، ونُنزله منزلته.",
    arabic: "",
    points: [],
    ref: "The questioning: Sahih al-Bukhari, Hadith 1369 — Sahih. The two names: Jami' at-Tirmidhi — outside the two Sahihs",
    strength: "The questioning: Sahih. The names: outside the two Sahihs",
    keys: ["munkar", "nakir", "grave angels", "questioning",
           "منكر", "نكير", "ملكا القبر", "سؤال القبر"]
  },
  {
    id: "ang-not-israfil-desc",
    group: "notest",
    order: 43,
    name: "The descriptions of Israfil's eyes and size",
    nameAr: "أوصاف عيني إسرافيل وعِظَم خلقه",
    role: "Widely repeated, and not from the two Sahihs",
    roleAr: "مشهورةٌ متداولة وليست من الصحيحين",
    detail: "That Israfil's eyes are fixed on the Throne and have never blinked, that his eyes are like two stars, the accounts of his size and of how many wings he has — none of this is in the Quran or in the two Sahihs, and some of it traces back to Israiliyyat. What IS established about him is on his own entry: his name, the Trumpet, the two blasts, the forty between them, and that its bearer is already waiting.",
    detailAr: "ما يُقال من أن عيني إسرافيل شاخصتان إلى العرش لم تطرفا قط، وأنهما كالكوكبين، وما يُروى في عِظَم خلقه وعدد أجنحته — ليس شيءٌ من ذلك في القرآن ولا في الصحيحين، وبعضه يرجع إلى الإسرائيليات. وأما الثابت عنه فمذكورٌ في مدخله: اسمه، والصور، والنفختان، والأربعون بينهما، وأن صاحبه قد استعدّ.",
    arabic: "",
    points: [],
    ref: "Not found in the Quran or the two Sahihs; parts of it are traced to Israiliyyat",
    strength: "Not established",
    keys: ["israfil eyes", "israfil size", "wings", "stars", "israiliyyat",
           "عينا إسرافيل", "عظم إسرافيل", "أجنحة", "الإسرائيليات"]
  }
];
