"""Serve the small copy of every background photograph to narrow screens.

A phone was downloading the same 1600-pixel photographs as a desktop and
drawing them 390 pixels wide. shrink-images.py writes a "-sm" copy of each
one; this writes the media query that uses them, straight from the rules
already in css/style.css, so a new background added tomorrow is covered by
running this again rather than by remembering to.

Only TOP-LEVEL rules are taken. A rule already inside a media query is
listed and left alone: overriding it here could put a photograph on a phone
that the design deliberately kept off it.

  python phone-photos.py           rewrite the generated block
  python phone-photos.py --check   fail if the block is out of date (CI)
"""
import io, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
CSS = os.path.join(HERE, "css", "style.css")
START = "/* ==== GENERATED by phone-photos.py — do not edit by hand ==== */"
END = "/* ==== END GENERATED phone photographs ==== */"
PHONE = "@media (max-width: 820px)"

text = io.open(CSS, encoding="utf-8").read()
body = text.split(START)[0].rstrip() + "\n"     # the stylesheet without the block

# --- read the rules --------------------------------------------------------
rules, skipped = [], []
i, depth, at_depth = 0, 0, None
sel_start = 0
while i < len(text):
    c = text[i]
    if c == "{":
        if depth == 0:
            sel = text[sel_start:i].strip()
        depth += 1
        if depth == 1 and sel.startswith("@"):
            at_depth = 1
        i += 1
        continue
    if c == "}":
        depth -= 1
        if depth == 0:
            at_depth = None
            sel_start = i + 1
        i += 1
        continue
    if c == "{" or depth > 1:
        i += 1
        continue
    i += 1

def rule_blocks(src):
    """(selector, declarations, inside_at_rule) for every rule."""
    out, i, n = [], 0, len(src)
    stack = []
    start = 0
    while i < n:
        ch = src[i]
        if ch == "{":
            head = src[start:i].strip()
            if head.startswith("@"):
                stack.append(head)
                start = i + 1
                i += 1
                continue
            j, d = i + 1, 1
            while j < n and d:
                if src[j] == "{": d += 1
                elif src[j] == "}": d -= 1
                j += 1
            out.append((head, src[i + 1:j - 1], list(stack)))
            i = j
            start = i
            continue
        if ch == "}":
            if stack: stack.pop()
            i += 1
            start = i
            continue
        i += 1
    return out

def strip_comments(s):
    """A rule's selector carries whatever comment stands above it; the
    generated block should show the selector alone."""
    while True:
        a = s.find("/*")
        if a < 0:
            break
        b = s.find("*/", a + 2)
        s = s[:a] + " " + (s[b + 2:] if b >= 0 else "")
    return " ".join(s.split())


USES = re.compile(r'url\("\.\./img/([A-Za-z0-9._-]+)\.jpg"\)')
lines = []
for sel, decls, inside in rule_blocks(body):
    m = [x for x in USES.finditer(decls)]
    if not m:
        continue
    smalls = [x for x in m if os.path.exists(os.path.join(HERE, "img", x.group(1) + "-sm.jpg"))]
    if not smalls:
        continue
    if inside:
        skipped.append(strip_comments(sel) + "   (inside " + inside[-1] + ")")
        continue
    decl = next(d for d in decls.split(";") if "background-image" in d)
    small = USES.sub(lambda x: 'url("../img/%s-sm.jpg")' % x.group(1),
                     " ".join(decl.split()))
    lines.append("  %s { %s; }" % (strip_comments(sel), small))

block = START + """
/* The same background photographs, at the size a phone actually draws them.
   Written from the rules above by ./phone-photos.py; the small copies are
   written by ./shrink-images.py. */
""" + PHONE + " {\n" + "\n".join(lines) + "\n}\n" + END + "\n"

out = body + "\n" + block

if "--check" in sys.argv:
    if text.rstrip() != out.rstrip():
        print("the phone photograph block is out of date — run ./phone-photos.py")
        sys.exit(1)
    print("phone photographs: up to date")
    sys.exit(0)

io.open(CSS, "w", encoding="utf-8", newline="").write(out)
print("wrote %d phone rules" % len(lines))
for s in skipped:
    print("  left alone:", s)
