"""Make the pictures small enough for a phone on mobile data.

WHY. Every photo here was dropped in at whatever size it came, and the
browser paid for it: a 97KB logo drawn at 46 pixels in the header of every
page, a 280KB app icon, and 340KB mosque photographs behind headings that a
phone shows 390 pixels wide. Nothing about the page looked wrong, so nothing
ever said it was.

WHAT IT DOES.
  * JPEG: re-encoded progressive at a sane quality, same dimensions. Written
    back only if the result is actually smaller.
  * A "-sm" copy of every photograph used as a full-width background, at most
    PHONE_W wide. css/style.css serves those to narrow screens (the block is
    generated by phone-photos.py).
  * PNG: the logo and the app icons are flat artwork with no partial
    transparency, so a 128-colour palette is indistinguishable from the
    original at the size it is drawn — and a tenth of the weight.

  python shrink-images.py           re-encode everything
  python shrink-images.py --check   fail if an image is over budget or a
                                    phone copy is missing (used by CI)
"""
import os, re, sys
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
IMG = os.path.join(HERE, "img")
PHONE_W = 820          # a 390pt phone at 2x, and still sharp at 3x scaled down
BUDGET_KB = 200        # nothing a reader downloads should be bigger than this
KEEP = ("logo-full.png", "logo-alt.png")   # unused originals, left untouched


def kb(p):
    return (os.path.getsize(p) + 1023) // 1024


def backgrounds():
    """Every photograph css/style.css or a page uses as a full-width
    background — those are the ones a phone should get a smaller copy of."""
    names = set()
    css = open(os.path.join(HERE, "css", "style.css"), encoding="utf-8").read()
    for m in re.finditer(r'url\("\.\./(img/[A-Za-z0-9._-]+\.jpg)"\)', css):
        names.add(os.path.basename(m.group(1)))
    for f in os.listdir(HERE):
        if f.endswith(".html"):
            page = open(os.path.join(HERE, f), encoding="utf-8").read()
            for m in re.finditer(r"url\('(img/[A-Za-z0-9._-]+\.jpg)'\)", page):
                names.add(os.path.basename(m.group(1)))
    return sorted(n for n in names if not n.endswith("-sm.jpg"))


LONG_EDGE = 1500       # nothing here is examined closely; it sits behind text


def jpeg(path, quality):
    """Re-encode in place, and keep stepping the quality down until the file
    is inside the budget. A budget that is raised to fit whatever is there
    is not a budget."""
    im = Image.open(path)
    before = os.path.getsize(path)
    if max(im.size) > LONG_EDGE:
        im = im.copy()
        im.thumbnail((LONG_EDGE, LONG_EDGE), Image.LANCZOS)
    tmp = path + ".tmp"
    for q in (quality, quality - 4, quality - 8, quality - 12):
        im.save(tmp, "JPEG", quality=q, optimize=True, progressive=True, subsampling=2)
        if os.path.getsize(tmp) <= BUDGET_KB * 1024:
            break
    # Only rewrite for a real saving. Re-encoding a JPEG always loses a
    # little, so running this twice must not quietly cost quality twice.
    if os.path.getsize(tmp) < before * 0.95:
        os.replace(tmp, path)
        return before // 1024 - os.path.getsize(path) // 1024
    os.remove(tmp)
    return 0


def small_copy(path, out):
    im = Image.open(path)
    if im.size[0] > PHONE_W:
        im = im.copy()
        im.thumbnail((PHONE_W, 10000), Image.LANCZOS)
    im.save(out, "JPEG", quality=78, optimize=True, progressive=True, subsampling=2)


def png(path):
    im = Image.open(path).convert("RGBA")
    h = im.split()[3].histogram()
    soft = sum(h[1:255])              # pixels that are part-way transparent
    if soft > 0.005 * im.size[0] * im.size[1]:
        return 0                      # soft edges: a palette would show them
    before = os.path.getsize(path)
    q = im.quantize(colors=128, method=Image.FASTOCTREE, dither=Image.FLOYDSTEINBERG)
    tmp = path + ".tmp"
    q.save(tmp, "PNG", optimize=True)
    if os.path.getsize(tmp) < before * 0.95:
        os.replace(tmp, path)
        return before // 1024 - os.path.getsize(path) // 1024
    os.remove(tmp)
    return 0


check = "--check" in sys.argv
bg = backgrounds()
problems, saved = [], 0

if check:
    for n in bg:
        sm = os.path.join(IMG, n[:-4] + "-sm.jpg")
        if not os.path.exists(sm):
            problems.append("no phone copy of " + n + " — run ./shrink-images.py")
    for f in sorted(os.listdir(IMG)):
        p = os.path.join(IMG, f)
        if os.path.isfile(p) and f not in KEEP and kb(p) > BUDGET_KB:
            problems.append("%s is %dKB, over the %dKB budget" % (f, kb(p), BUDGET_KB))
    for line in problems:
        print(line)
    print("images: " + ("FAILED" if problems else "within budget"))
    sys.exit(1 if problems else 0)

for f in sorted(os.listdir(IMG)):
    p = os.path.join(IMG, f)
    if not os.path.isfile(p) or f in KEEP or f.endswith("-sm.jpg"):
        continue
    if f.endswith(".jpg"):
        w = Image.open(p).size[0]
        saved += jpeg(p, 80 if w >= 1000 else 76)
    elif f.endswith(".png"):
        saved += png(p)

for n in bg:
    src = os.path.join(IMG, n)
    if os.path.exists(src):
        small_copy(src, os.path.join(IMG, n[:-4] + "-sm.jpg"))

total = sum(kb(os.path.join(IMG, f)) for f in os.listdir(IMG)
            if os.path.isfile(os.path.join(IMG, f)))
print("saved %dKB; img/ is now %dKB, phone copies: %s" % (saved, total, ", ".join(bg)))
